### ISSUE TITLE
Leaked Channels

### ISSUE THREAD

**Issue by Lankester** [davidstump/SwiftPhoenixClient#109]
My application joins and leaves different channels depending on where the user is in the application.

During some profiling tests I noticed some leaked objects, that appeared to be generated following calls to channel.leave(). Originally I assumed it was my code but in the end I managed to find the following in the memory debugger which seems to indicate an orphaned channel, several closure contexts, and cyclic references to PhxTimer and Push. Essentially the channel is never deallocated and however many channels the application joins they always persist in memory.

<img width="753" alt="memory_graph" src="https://user-images.githubusercontent.com/29251536/44464001-6db47d00-a611-11e8-86f1-5455b4892524.png">

I have managed to solve the issue with the following changes https://github.com/Lankester/SwiftPhoenixClient/commit/0c5c263776238bf0af8c9cc1e20937e739294eab but despite the tests passing I am not sure it is the best way.

If it turns out to be a reasonable solution, I'd be happy to submit a PR.

**Comment by dsrees** [comment]
Hmmm looks like a reasonable solution, but I'm curious if there's a better way we can manage channel instances. I'll take a look into it. Thanks for reporting this!

**Comment by darrenclark** [comment]
Ran into this issue as well.

I wondering an approach like @Lankester's https://github.com/Lankester/SwiftPhoenixClient/commit/0c5c263776238bf0af8c9cc1e20937e739294eab , but using `weak` references would be a good option?

I think there is a potential for some subtle crashes with using `unowned`.  For example, changing [`Push.channel`](https://github.com/davidstump/SwiftPhoenixClient/blob/b2e7b69607d5fd6f8a7ec05f063f78012ba9551a/Sources/Push.swift#L14) to `unowned` could cause a crash along the lines of:

1. a `Push` object is created and [stored on a `Channel`](https://github.com/davidstump/SwiftPhoenixClient/blob/b2e7b69607d5fd6f8a7ec05f063f78012ba9551a/Sources/Channel.swift#L55-L59)
2. the `Push.send()` function is called, starting the timeout timer [here](https://github.com/davidstump/SwiftPhoenixClient/blob/b2e7b69607d5fd6f8a7ec05f063f78012ba9551a/Sources/Push.swift#L125)
3. The parent `Channel` gets `deinit`'d (maybe the socket is closed, etc..)
4. Reference to `Push` object is still strongly held by the `timeoutTimer` `NSTimer` [here](https://github.com/davidstump/SwiftPhoenixClient/blob/b2e7b69607d5fd6f8a7ec05f063f78012ba9551a/Sources/Push.swift#L198)
5. When the `timeoutTimer` fires, it calls into `trigger(_:payload:)`, which uses `self.channel` [here](https://github.com/davidstump/SwiftPhoenixClient/blob/b2e7b69607d5fd6f8a7ec05f063f78012ba9551a/Sources/Push.swift#L235), causing a crash (since it was `deinit`'d in step 3)

Thoughts on using `weak` instead?  I can try to put together a PR for using `weak`

**Comment by dsrees** [comment]
I would be happy to review a PR if you could put one together @darrenclark. I was thinking along the same lines. I didn't think simply `unowned` would solve the problem.

**Comment by darrenclark** [comment]
Cool, i'll take a stab at it

**Comment by Lankester** [comment]
Sorry, I missed the `timeoutTimer` closure calling `self` in `Push`. `weak` should do it.

**Comment by dsrees** [comment]
Not a problem @Lankester! We still appreciate you reporting the issue! I'll be sure to get a release out as soon as a fix is approved.
