### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by imann24** [davidstump/SwiftPhoenixClient#121]
Hi, does this package support tvOS?

**Comment by dsrees** [comment]
@imann24 I have not personally tested this or made efforts to guarantee its support. Feel free to try it out and let me know how it goes. I'd be happy to have support added

**Comment by jklp** [comment]
@imann24 I've created a PR at #141 which is now running on our live Apple TV app (zova.com).  The only problem is the Travis build is failing because Jazzy was commented out in the `Gemfile` in the prior commit without the `Gemfile.lock` being updated (8e476c284542c9b7ee7fa8e52470c933463dd20c).  

I'm hesitant to add an updated `Gemfile.lock` to my PR in case there's something which needs to be resolved on your end - but if you could have a look and let me know if they're any changes I need to make before it's merged?

Thanks
Jerrold

**Comment by imann24** [comment]
Hi! I haven't had the chance to integrate our tvOS app w/ this client (or with Phoenix Framework unfortunately). 

If I happen to start the work back up, more than happy to dig in to your PR. Otherwise, not sure I'm a great subject matter expert here.

I assume @dsrees can speak to the Travis issue?

**Comment by jklp** [comment]
Oh my apologies, I replied to the wrong person! Yes was meant to @reply dsress

**Comment by imann24** [comment]
No worries!

**Comment by dsrees** [comment]
Hey guys, sorry for the delay and for not getting to that PR sooner. Jazzy was messing up something a few months back, i believe it's safe to get it updated. I'll take a look into this

**Comment by dsrees** [comment]
Just released v1.1.1 with @jklp changes
