### ISSUE TITLE
Add to Cocoapods

### ISSUE THREAD

**Issue by davidstump** [davidstump/SwiftPhoenixClient#3]
Would be ideal to allow people to pull this in via Cocoapods.

**Comment by optikfluffel** [comment]
:+1:

**Comment by mudphone** [comment]
And maybe Carthage? Also, I've started experimenting with pulling in the websockets code via the Starscream pod. It seems to work fine.

**Comment by mudphone** [comment]
/me reading all the CocoaPods documentation...

@davidstump What version would you like to start with?

**Comment by mudphone** [comment]
Got the library working via a test CocoaPod. I'll clean it up and submit a PR.

<img width="495" alt="screen shot 2015-08-25 at 1 07 21 am" src="https://cloud.githubusercontent.com/assets/24647/9465275/faad12fc-4ac6-11e5-9f28-0d41c5fa4875.png">

**Comment by davidstump** [comment]
Awesome!!

**Comment by mudphone** [comment]
:rocket: The version number in the [podspec file](https://github.com/mudphone/SwiftPhoenixChannels/blob/package/SwiftPhoenixClient.podspec) defaults to 0.1.0. Maybe it should be 0.3.0, since there was (0.1.0) your first version, (0.2.0) my PR for Swift 1.2/Phoenix 0.17, and (0.3.0) this pod? 

Another idea would be to keep the 0.X version number parallel to the Phoenix release.

I haven't updated or linted the podspec yet either. I'll do that soon.

I've also written up [some brief instructions](https://github.com/mudphone/SwiftPhoenixChannels/blob/package/README_pods.md) on how to install the pod from a local directory, so you don't have to push it to a repo. This is all on my fork's `package` branch right now. I'll PR when it's cleaner.

**Comment by mudphone** [comment]
I wrote up pull request to try out CocoaPods in #6 . Let me know what you think :)

**Comment by davidstump** [comment]
Pulled in - Thanks again :)

**Comment by davidstump** [comment]
BTW - Can't get to it at the moment, but I can update the docs to reference the new CocoaPod installation/structure.

**Comment by mudphone** [comment]
:rocket: ! I can help with that too. Also, start reading up on pushing to CocoaPods trunk and maybe open up an issue for comments.
